item {
  id: 1
  name: 'Artefacto'
}

item {
  id: 2
  name: 'E.coli'
}

item {
  id: 3
  name: 'Trichuris trichura'
}

item {
  id: 4
  name: 'Ascaris lumbricoides'
}

item {
  id: 5
  name: 'Uncinarias'
}

item {
  id: 6
  name: 'Diphyllobothrium latum'
}

item {
  id: 7
  name: 'Taenia'
}

item {
  id: 8
  name: 'Balantidium coli'
}

item {
  id: 9
  name: 'Hymenolepis nana'
}

item {
  id: 10
  name: 'Schistosoma mansoni'
}

item {
  id: 11
  name: 'Enterobius vermicularis'
}

item {
  id: 12
  name: 'Amebas'
}

item {
  id: 13
  name: 'Giardia'
}
